port: 8888
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    hard_wrap: false
    toc_levels: '1'
highlighter: rouge
plugins: ['jekyll-paginate', 'jekyll-babel', 'jekyll-github-metadata', 'bourbon', 'neat']
exclude: [_drafts, Rakefile, node_modules, Gemfile, Gemfile.lock, README.md]

# Current RethinkDB version
version:
    # major version number, used primarily for linking to GitHub feature branches
    #   -> e.g. 1.2, 1.3
    major: 2.3
    # full version number, include point releases and build tags, used for download links
    #   -> e.g. 1.2.1-3, 1.3.0
    full: 2.3.6
    # ---
    # human-readable version number (no build tags), used for marketing copy
    #   -> e.g. 1.2.1, 1.3
    human: 2.3
    codename: Fantasia
    release_post: /blog/2.3.6-release
rethinkdb_users: "100,000"
github_stars: "22k"

sass:
    sass_dir: _sass

# Blog settings
paginate: 5
paginate_file: blog/index.html
paginate_path: /blog/page:num
permalink: /blog/:title
excerpt_separator: <!--more-->

# RSS settings
rss:
    name: "RethinkDB: the open-source database for the realtime web"
    description: News and updates from the RethinkDB team.
    url: https://rethinkdb.com

algolia:
    app_id: U39D71436I

# GitHub settings
github:
    source:
        branch: master